### ISSUE TITLE
doxygen bug

### ISSUE THREAD

**Issue by carsten-kuebler** [OpenSimulationInterface/proto2cpp#6] opened 2018-12-09 17:29 UTC
Large proto documentations may lead to some unexpected '*' or previous '///' in the html documentation.

**Comment by jdsika** [comment] 2019-09-11 11:39
@vkresch is this still an issue?

**Comment by vkresch** [comment] 2019-09-11 17:58
@carsten-kuebler can you provide a link on which specific html page you saw this behaviour?

**Comment by vkresch** [comment] 2019-09-17 12:21
For now I will close it since I can't see or reproduce the bug.

**Closed as completed by vkresch** 2019-09-17 12:21 UTC
Labels: bug
